### ISSUE TITLE
求问如何配置Diosic的nginx，以下配置行不通，请帮我补充修改一些参数

### ISSUE THREAD

**Issue by SyberRabbit** [Reknij/diosic#3]
location ~ /diosic {
    proxy_pass http://127.0.0.1:40177;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

**Comment by Reknij** [comment]
端口号改为3177试试，默认端口号是3177，如果没有改过端口号的话。还是不行的话试试将127.0.0.1改为0.0.0.0再试试看。

是使用docker部署对吧？data和library目录改为你的目录时，选择已存在的，未存在的路径的好像不会自动创建。

**Comment by 9563067** [comment]
我用的是1panel自动部署，如图1和2
项目本身没问题，可以直接用40177访问。nginx单独用/代理diosic也没问题，如图3（域名是用内网adguard重写的）。但就是用二级路径来代理就全是404，如图4和5
![图片](https://github.com/user-attachments/assets/d9520f3c-7573-478f-a532-98196932b91a)
![图片](https://github.com/user-attachments/assets/8b230738-c5d1-4105-8141-e1a099bc8b09)
![图片](https://github.com/user-attachments/assets/5b152eda-d70a-4c2e-b01e-2fea10890d01)
![图片](https://github.com/user-attachments/assets/94cacd5d-8cb7-42a8-b99f-1a78851a5eab)
![图片](https://github.com/user-attachments/assets/0fd465a1-a5e1-4515-be68-388dfa76e3ac)

**Comment by SyberRabbit** [comment]
> 端口号改为3177试试，默认端口号是3177，如果没有改过端口号的话。还是不行的话试试将127.0.0.1改为0.0.0.0再试试看。
> 
> 是使用docker部署对吧？data和library目录改为你的目录时，选择已存在的，未存在的路径的好像不会自动创建。

我用的是1panel自动部署，如图1和2
项目本身没问题，可以直接用40177访问。nginx单独用/代理diosic也没问题，如图3（域名是用内网adguard重写的）。但就是用二级路径来代理就全是404，如图4和5
我来找您是因为alist也有相关问题，但也有解决方法，多加一些参数，以及修改文件配置就可以解决，但这已经触及到我知识盲区了，教程来自https://github.com/alist-org/alist/discussions/4201。
我认为Diosic也会是这么麻烦，所以只能找作者。。
![图片](https://github.com/user-attachments/assets/d9520f3c-7573-478f-a532-98196932b91a)
![图片](https://github.com/user-attachments/assets/8b230738-c5d1-4105-8141-e1a099bc8b09)
![图片](https://github.com/user-attachments/assets/b75b6628-e7a5-4af6-92cb-6fa4cb91789c)
![图片](https://github.com/user-attachments/assets/94cacd5d-8cb7-42a8-b99f-1a78851a5eab)
![图片](https://github.com/user-attachments/assets/0fd465a1-a5e1-4515-be68-388dfa76e3ac)

**Comment by Reknij** [comment]
@9563067 

由于使用的是打包好的SPA网页，所以目前不支持二级路径下，也许你可以使用子域名来区分你的服务，例如：
```
server {
    server_name diosic.g470.com;
    listen  80;

    location / {
        proxy_pass http://127.0.0.1:40177/;
    }
}
```

如果你由于一些原因还是要用二级域名来访问的话。那么可能需要花你一点时间：
前置：
- 安装好node.js，目前22版就行。
- 有一些文本编辑器，vim都行。

开始：
1. `git clone https://github.com/Reknij/diosic.git` Clone本项目下来
2. `cd ./web` 切换到源码`web`子文件夹
3. `npm install`或`pnpm install` 下载全部依赖。
4. `vim nuxt.config.ts` 使用`Vim`编辑Nuxt配置文件，随便一个编辑器就行，VSCode就`code nuxt.config.ts`，改成以下：
  ```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["@nuxt/ui"],
  ui: {
    icons: ['mdi']
  },
  app: {
    baseURL: '/diosic',
    head: {
      title: 'Diosic',
      link: [
        { rel: 'icon', type: 'image/svg', href: '/favicon.svg' }
      ]
    }
  },
  ssr: false,
  runtimeConfig: {
    public: {
      baseUrl: '/diosic',
      devBaseUrl: 'http://127.0.0.1:3177'
    }
  },
  nitro: {
    preset: 'static',
  },
})
  ```

其实就是*加了/更改（注意大小写）*:
  ```
export default defineNuxtConfig({
  ...,
  app: {
    ...,
    baseURL: '/diosic',
  },
  runtimeConfig: {
    public: {
      ...,
      baseUrl: '/diosic',
    }
  },
})
  ```

其中`/diosic`可以改为你想要的二级目录

5. `npm run generate`或`pnpm generate` 打包网页。输出目录是`./.output/public/`，`public`这个文件夹就是前端网页了。先重命名为`custom_webpage`，放到你想要的目录下。
6. *关于docker启动容器时，记得设置环境变量，`PUBLIC_URL`为你的二级路径*，以下展示直接docker run启动:
  ```
docker run -d \
  --name diosic \
  -v /my_data:/data \
  -v /my_library:/library \
  -v /custom_webpage:/webpage \
  -p 40177:3177 \
  -e PUBLIC_URL=/diosic \
  jinker25/diosic
  ```
其中`/my_data`和`/my_library`为你的相应路径。而`/custom_webpage`则是上一步的网页存放路径。

**Comment by SyberRabbit** [comment]
> @9563067
> 
> 由于使用的是打包好的SPA网页，所以目前不支持二级路径下，也许你可以使用子域名来区分你的服务，例如：
> 
> ```
> server {
>     server_name diosic.g470.com;
>     listen  80;
> 
>     location / {
>         proxy_pass http://127.0.0.1:40177/;
>     }
> }
> ```
> 
> 如果你由于一些原因还是要用二级域名来访问的话。那么可能需要花你一点时间： 前置：
> 
>     * 安装好node.js，目前22版就行。
> 
>     * 有一些文本编辑器，vim都行。
> 
> 
> 开始：
> 
>     1. `git clone https://github.com/Reknij/diosic.git` Clone本项目下来
> 
>     2. `cd ./web` 切换到源码`web`子文件夹
> 
>     3. `npm install`或`pnpm install` 下载全部依赖。
> 
>     4. `vim nuxt.config.ts` 使用`Vim`编辑Nuxt配置文件，随便一个编辑器就行，VSCode就`code nuxt.config.ts`，改成以下：
> 
> 
> ```
> // https://nuxt.com/docs/api/configuration/nuxt-config
> export default defineNuxtConfig({
> devtools: { enabled: true },
> modules: ["@nuxt/ui"],
> ui: {
>   icons: ['mdi']
> },
> app: {
>   baseURL: '/diosic',
>   head: {
>     title: 'Diosic',
>     link: [
>       { rel: 'icon', type: 'image/svg', href: '/favicon.svg' }
>     ]
>   }
> },
> ssr: false,
> runtimeConfig: {
>   public: {
>     baseUrl: '/diosic',
>     devBaseUrl: 'http://127.0.0.1:3177'
>   }
> },
> nitro: {
>   preset: 'static',
> },
> })
> ```
> 
> 其实就是_加了/更改（注意大小写）_:
> 
> ```
> export default defineNuxtConfig({
> ...,
> app: {
>   ...,
>   baseURL: '/diosic',
> },
> runtimeConfig: {
>   public: {
>     ...,
>     baseUrl: '/diosic',
>   }
> },
> })
> ```
> 
> 其中`/diosic`可以改为你想要的二级目录
> 
>     5. `npm run generate`或`pnpm generate` 打包网页。输出目录是`./.output/public/`，`public`这个文件夹就是前端网页了。先重命名为`custom_webpage`，放到你想要的目录下。
> 
>     6. _关于docker启动容器时，记得设置环境变量，`PUBLIC_URL`为你的二级路径_，以下展示直接docker run启动:
> 
> 
> ```
> docker run -d \
> --name diosic \
> -v /my_data:/data \
> -v /my_library:/library \
> -v /custom_webpage:/webpage \
> -p 40177:3177 \
> -e PUBLIC_URL=/diosic \
> jinker25/diosic
> ```
> 
> 其中`/my_data`和`/my_library`为你的相应路径。而`/custom_webpage`则是上一步的网页存放路径。

非常感谢您做了那么多，我先save下来，等有精力后我试一下😂
